# Generated by Django 6.0.5 on 2026-07-06 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='banner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='season',
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_product_review'),
        ),
    ]
