# Generated by Django 6.0.5 on 2026-07-06 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_productreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='banner',
            name='season',
            field=models.CharField(choices=[('default', 'Default'), ('valentine', 'Valentine'), ('salah', 'Salah'), ('christmas', 'Christmas'), ('newyear', 'New Year')], default='default', max_length=50),
        ),
    ]
