# Generated by Django 6.0.5 on 2026-07-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_banner_created_at_banner_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
