# Generated by Django 6.0.5 on 2026-07-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_ordertracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at']},
        ),
    ]
