# Generated by Django 6.0.5 on 2026-07-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_alter_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
