# Generated by Django 6.0.5 on 2026-07-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_remove_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='payment_status',
        ),
    ]
