# Generated by Django 6.0.5 on 2026-07-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0017_rename_status_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='status',
        ),
    ]
