# Generated by Django 6.0.5 on 2026-07-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0020_order_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shipping_address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
