# Generated by Django 6.0.5 on 2026-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_transaction_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
