# Generated by Django 6.0.5 on 2026-07-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0022_alter_transaction_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
