# Generated by Django 6.0.5 on 2026-07-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0023_transaction_city_transaction_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
