# Generated by Django 6.0.5 on 2026-07-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0030_stockmovement_note_stockmovement_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='note',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='order',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.product'),
        ),
    ]
