# Generated by Django 6.0.5 on 2026-08-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0033_remove_deliveryupdate_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='courier',
            field=models.CharField(blank=True, choices=[('gig_logistics', 'GIG Logistics'), ('dhl_express_nigeria', 'DHL Express Nigeria'), ('fedex_nigeria', 'FedEx Nigeria'), ('ups_nigeria', 'UPS Nigeria'), ('abc_cargo_express', 'ABC Cargo Express'), ('kwik_delivery', 'Kwik Delivery'), ('sendbox', 'Sendbox'), ('kobo360', 'Kobo360'), ('Local_delivery', 'Local_delivery'), ('red_star_express', 'Red Star Express'), ('tranex', 'Tranex (Trans-Nationwide Express Plc)')], default='', max_length=100),
        ),
    ]
