# Generated by Django 6.0.5 on 2026-09-09 21:31

import shop_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0034_alter_shipment_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(storage=shop_app.storage.ProductMediaCloudinaryStorage(), upload_to='product_media/'),
        ),
    ]
