# Generated by Django 6.0.5 on 2026-09-10 16:00

import shop_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0035_alter_order_delivery_fee_alter_productmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, null=True, storage=shop_app.storage.ProductMediaCloudinaryStorage(), upload_to='product_media/'),
        ),
    ]
