# Generated by Django 6.0.5 on 2026-09-12 20:32

import shop_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0037_alter_contactmessage_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=shop_app.storage.ProductMediaCloudinaryStorage(), upload_to='product_media/'),
        ),
    ]
